name: Crowdin Action

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "source/about/*.md"
      - "source/api/*.md"
      - "source/docs/*.md"
      - "source/*.md"

jobs:
  upload-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: crowdin/github-action@v1
        with:
          upload_translations: false
          download_translations: false
          upload_sources: true
          config: "crowdin.yml"
          crowdin_branch_name: master
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
