name: "PR Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v4
        id: label-the-PR

      - name: print the labels
        env:
          all_labels: ${{steps.label-the-PR.outputs.all-labels}}
          new_labels: ${{steps.label-the-PR.outputs.new-labels}}
        run: |
          echo "all_labels, $all_labels"
          echo "new_labels, $new_labels"

      - name: set the SUMMARY
        env:
          all_labels: ${{steps.label-the-PR.outputs.all-labels}}
          new_labels: ${{steps.label-the-PR.outputs.new-labels}}
        run: |
          echo "### All labels" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "$all_labels" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### New labels" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "$new_labels" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
